### PR TITLE
Remove direct dependency on golang.org/x/exp

### PR DESCRIPTION
**Pull request by ryanslade**
Most of what we need is already in the stdlib.

### CODE REVIEW

**Review by andrew-farries — COMMENTED** [review]
Would it be worth updating to Go 1.23 instead so that we can use the built-in iterators?

**Comment by ryanslade** [comment]
Sure, we can do that but it forces anyone using pgroll as a library to upgrade too and may force us to tag a new version.

**Comment by andrew-farries** [comment]
I think we should upgrade. We should tag a 0.7 release soon anyway.

**Comment by ryanslade** [comment]
We'll upgrade to Go 1.23 instead and use the new sodlib packages.

**Pull request closed without merging**
