### PR TITLE
Update `docker-compose.yml`

### PR DESCRIPTION
**Pull request by andrew-farries**
Update `docker-compose.yml`

* Remove redundant `version` field.
* Change the port number
* Change the image version to Postgres 17.
* Use an anonymous volume so that it can be cleaned up with `docker compose rm -v`

### CODE REVIEW

**Review by exekias — APPROVED** [review]
will te change in port impact docs? I guess it would require to manually change some URL?

**Comment by andrew-farries** [comment]
The docker compose setup isn't discussed in the docs, so no need to change anything.

**Comment by exekias** [comment]
I guess it still means we deviate from defaults? now setting a URL will be required for init and so, what's the rationale behind the port change?

**Comment by andrew-farries** [comment]
Sorry, didn't see your comment before I merged.

https://github.com/xataio/pgroll/pull/402 changes the port back to `5432`. The motivation was to avoid colliding with other existing Postgres instances that might be running, but changing the port here isn't the best way to solve that.

**Pull request merged**
